### ISSUE TITLE
Is there a way to combine all CSS files into one and all JS files into one 

### ISSUE THREAD

**Issue by zamamohammed** [Adobe-Marketing-Cloud/aem-sightly-sample-todomvc#1]
Hi,

I wanted to know if there a way to combine all CSS files into one and all JS files into one.

**Comment by gabrielwalt** [comment]
This is exactly what the client libraries do.

See [`clientlib`](src/jcr_root/etc/designs/todo/clientlib), there are two JavaScript files, and one dependency, but when accessing that path on your local instance, this is served as only one JS file: [clientlib.js](http://localhost:4502/etc/designs/todo/clientlib.js).
