### ISSUE TITLE
ReferenceError: "granite" is not defined after installing AEM 6.0 SP2

### ISSUE THREAD

**Issue by grudzien44140** [Adobe-Marketing-Cloud/aem-sightly-sample-todomvc#4]
After installing AEM 6.0 SP2 the todo example was working.  After restarting my AEM server instance the example stopped working with the error pasted below.  If I build a new AEM server instance from scratch, install sp2 and then install the TODO package, the site works, however if I restart the server instance the todo app stops working.

org.apache.sling.api.SlingException: Cannot get DefaultSlingScript: org.mozilla.javascript.EcmaError: ReferenceError: "granite" is not defined. (/apps/todo/components/page/page.html#44)

AEM 6.0 SP1 does not cause this issue.  It appears to only happen after AEM 6.0 SP2 is installed.

**Comment by raducotescu** [comment]
It seems that this is a bug with the `io.sightly.js.bundle`, version 1.0.16.CQ600-B0006. More specifically JavaScript Use-API dependencies are not handled correctly when a script depends on another sibling script with the same name as a script provided by the currently executed component.

**Comment by raducotescu** [comment]
Closing this issue as it's not a demo app problem, but rather a bug in the `io.sightly.js.bundle`. AEM 6.1 will provide the Sightly implementation from Apache Sling where this bug has been fixed - see [SLING-4578](https://issues.apache.org/jira/browse/SLING-4578).

**Comment by gompinfo** [comment]
Thank you for the info raducotescu! Is there any workaround until sling and aem will be updated with the fix? Because I would like to evaluate slightly for future use in AEM forms.
