### ISSUE TITLE
Where to create an issue (with Sightly in aem?)

### ISSUE THREAD

**Issue by josephh** [Adobe-Marketing-Cloud/aem-sightly-sample-todomvc#9]
H, apologies to create an issue here that's not directly related to the sample todomvc.  I'm seeing an issue using Sightly in aem but I don't know where to post a bug report.  I created a post on the [adobe help forum](http://help-forums.adobe.com/content/adobeforums/en/experience-manager-forum/adobe-experience-manager.topic.html/forum__fbpk-i_am_seeingsomeune.html) but I don't know if that gets much use.

**Comment by raducotescu** [comment]
Hello Joseph,

If you need to file an AEM issue then please use DayCare, as instructed at https://helpx.adobe.com/experience-manager/kb/accessing-aem-support-portal.html.

**Comment by josephh** [comment]
ok thanks @raducotescu will do that in future.
